# Generated by Django 5.0.1 on 2024-03-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnemRespostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('resposta', models.CharField()),
                ('ingles', models.BooleanField(default=False)),
                ('espanhol', models.BooleanField(default=False)),
                ('numero_questao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntas', models.TextField()),
                ('respostas', models.TextField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flash.pagina')),
            ],
        ),
        migrations.CreateModel(
            name='Simulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('alternativa_a', models.TextField()),
                ('alternativa_b', models.TextField()),
                ('alternativa_c', models.TextField()),
                ('alternativa_d', models.TextField()),
                ('correta', models.TextField(default='a')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulado', to='flash.pagina')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arroba', models.TextField(unique=True)),
                ('tipo_user', models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=10)),
                ('foto_perfil', models.ImageField(default='perfil/default.jpg', upload_to='perfil/')),
                ('paginas', models.ManyToManyField(related_name='usuarios', to='flash.pagina')),
                ('paginas_compartilhadas', models.ManyToManyField(blank=True, related_name='paginas_compartilhadas', to='flash.pagina')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticasSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_simulado', to='flash.pagina')),
                ('questoes_corretas', models.ManyToManyField(blank=True, related_name='tentativas_corretas', to='flash.simulados')),
                ('questoes_erradas', models.ManyToManyField(blank=True, related_name='tentativas_erradas', to='flash.simulados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_simulado', to='flash.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticasEnem_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_usuario', models.CharField(default='A')),
                ('numero_questao', models.IntegerField(default=1)),
                ('correto_errada', models.BooleanField(default=True)),
                ('idioma_escolhido', models.IntegerField(default=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_enem', to='flash.enemrespostas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enem_usuario', to='flash.usuario')),
            ],
        ),
    ]
