# Generated by Django 5.0.1 on 2024-03-18 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_alter_estatisticassimulado_compartilhada_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticasenem_usuario',
            name='data_da_tentativa',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
